name: flutter_responsive_login_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  rename: ^3.0.2
  flare_flutter: ^3.0.2
  lottie: ^3.0.0
  getwidget: ^4.0.0  # Use the specific version
  intl: ^0.19.0
  image_picker: ^1.1.2
  quickalert: ^1.1.0
  date_picker_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/signin_balls.png
    - assets/svgs/
